export const foodItems = [
  {
    id: 1,
    name: "Double Patty Veg Burger",
    description: "A delicious double patty stacked with fresh veggies and sauces.",
    price: "$40.00",
    image: "/src/assets/Double patty veg burger.jpeg",
  },
  {
    id: 2,
    name: "Chicken Burger",
    description: "Nestled between two golden, toasted brioche buns, tender grilled chicken, fresh lettuce, and creamy sauces for a savory delight.",
    price: "$17.56",
    image: "/src/assets/Chicken Burgers.jpeg",
  },
  {
    id: 3,
    name: "Pineapple Pizza",
    description: "Embark on a culinary journey to a tropical haven...",
    price: "$11.02",
    image: "/src/assets/pineapple pizza.jpeg",
  },
 {
    id: 4,
    name: "aloo tikki burger",
    description: "Aloo Tikki Burger with crispy potato patties, zesty sauces, and fresh veggies.",
    price: "$50.00",
    image: "/src/assets/aloo tikki burger.jpeg",
  },
  {
    id: 5,
    name: "green salad",
    description: " Garden Fresh Green Salad , a vibrant bowl of crisp lettuce, grilled chicken, veggies, and zesty dressing.",
    price: "$45.00",
    image: "/src/assets/green salad.jpeg",
  },
  {
    id: 6,
    name: "honey bread",
    description: "lovingly crafted using premium flour and a generous drizzle of honey.",
    price: "$15.00",
    image: "/src/assets/honey bread.jpeg",
  },
  {
    id: 7,
    name: "momos",
    description: "Accompanied by our signature dipping sauce, burst of flavorful spices and tender fillings.",
    price: "$50.00",
    image: "/src/assets/momos.jpeg",
  },
  {
    id: 8,
    name: "pineapple soup",
    description: "Nestled between two golden, toasted brioche bunsCrafted with the freshest, sun-kissed pineapples",
    price:"$11.02",
    image: "/src/assets/pineapple soup.jpeg",
  },
  {
    id: 9,
    name: "pancakes",
    description: "Fluffy Morning Delight, golden pancakes stacked high and topped with syrup, butter.",
    price: "$12.20",
    image: "/src/assets/pancakes.jpeg",
  },
];
